language: java

jdk:
  - openjdk8

sudo: required

before_install:
  - sudo apt-get -y install npm
  - npm --prefix goobi-viewer-core/ install

script:
  - cd goobi-viewer-core; ant war-internal junit-simple javadoc
  - npm run docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
